name:                servant-validate
version:             0.1.0.0
github:              "mstksg/servant-validate"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) 2021 Justin Le"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Chekc static properties of servant APIs
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  A package with "test suites" to help verify that your servant APIs are valid at
  compile-time.

  Currently the only property tested is that there are no duplicated paths.

  ```haskell
  data DeadlySinEnum = Lust | Gluttony | Greed | Sloth | Wrath | Envy | Pride

  type MathApi  = "sin" :> ReqBody '[JSON] Double        :> Post '[JSON] NoContent
  type SatanApi = "sin" :> ReqBody '[JSON] DeadlySinEnum :> Post '[JSON] NoContent

  type MyApi = MathApi :<|> SatanApi

  myApi :: Proxy MyApi
  myApi = Proxy

  validMyApi :: ValidApiTree MyApi
  validMyApi = validApiTree myApi
  ```

  ```haskell
  warning: [-Wdeferred-type-errors]
      • Duplicate method in API at path /sin: "POST"
      • In the expression: validApiTree myApi
        In an equation for ‘validMyApi’: validMyApi = validApiTree myApi
  ```

dependencies:
- base >= 4.7 && < 5
- servant
- text
- containers

library:
  source-dirs: src

tests:
  servant-validate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-validate
    - hspec
    - should-not-typecheck
